application: bingousie
version: 1
runtime: python
api_version: 1


handlers:
- url: /_ah/login_required
  script: do_openid_login.py

- url: /media
  static_dir: static
  
- url: /.*
  script: app.py
  
builtins:
- datastore_admin: on